# Generated by Django 3.0.11 on 2021-01-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('cover', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='cover')),
                ('description', models.TextField(blank=True, max_length=225)),
                ('body', models.TextField(max_length=5500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.Story')),
                ('users', models.ManyToManyField(related_name='requirement_story_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='stories.Story')),
                ('users', models.ManyToManyField(related_name='requirement_story_dis_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
