# Generated by Django 3.0.11 on 2021-01-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.Story'),
        ),
        migrations.AddField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='requirement_story_likes', to='stories.Story'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='stories.Story'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='users',
            field=models.ManyToManyField(related_name='requirement_story_dis_likes', to='stories.Story'),
        ),
    ]
