# Generated by Django 3.0.10 on 2020-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
