# Generated by Django 3.0.10 on 2020-11-24 10:15

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20201123_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='cover'),
        ),
    ]
