# Generated by Django 3.0.11 on 2021-01-10 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_auto_20210110_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='users',
            field=models.ManyToManyField(related_name='requirement_story_dis_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='requirement_story_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
