# Generated by Django 3.0.11 on 2020-12-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20201206_1923'),
        ('stories', '0003_auto_20201124_1715'),
    ]

    operations = [
    ]
