# Generated by Django 3.0.10 on 2020-09-29 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storys',
            new_name='Story',
        ),
    ]
