# Generated by Django 3.0.11 on 2020-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default="Hi, I'm using Djraft.", max_length=255, verbose_name='About User'),
        ),
    ]
