# Generated by Django 3.0.11 on 2020-12-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201124_1753'),
        ('users', '0003_user_about'),
    ]

    operations = [
    ]
