# Generated by Django 3.0.11 on 2020-12-17 05:39

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20201207_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='avatar'),
        ),
    ]
