# Generated by Django 3.0.11 on 2020-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201217_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Hi, there.', max_length=160, verbose_name='UserBio'),
        ),
    ]
