# Generated by Django 3.0.10 on 2020-09-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='cover',
        ),
    ]
