# Generated by Django 3.0.10 on 2020-09-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200917_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='cover_2',
            field=models.ImageField(default=None, upload_to='images/upload'),
        ),
    ]
