# Generated by Django 3.0.10 on 2020-09-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200923_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_2',
        ),
    ]
