# Generated by Django 3.0.10 on 2020-09-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_cover_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_2',
            field=models.ImageField(default=None, upload_to='images/upload'),
        ),
    ]
