# Generated by Django 3.0.10 on 2020-09-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_cover_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_2',
        ),
    ]
